version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
      
    volumes:
      - ./next-app/app:/app/app
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - face-2-simpson-network

  python-server:
      container_name: python-server
      build:
        context: ./python-server
        dockerfile: Dockerfile

      volumes:
        - ./python-server:/app
      restart: always
      ports:
        - 8000:8000
      environment:
        - ENVIRONMENT=development
      networks:
        - face-2-simpson-network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  face-2-simpson-network:
    external: true
    driver: bridge
    
