AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python 3.10 based SAM Template for PyTorch ML Prediction Model Server

Resources:
  PredictImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      Timeout: 30
      PackageType: Image
      ImageConfig:
        Command: ['app.lambda_predict_image']
      # need this to run docker on mac
      # Architectures: ['arm64']
      Environment:
        Variables:
          AMAZON_BUCKET: face-2-simpson-imgs
      Events:
        ApiEndpoint:
          Type: HttpApi
          Properties:
            Path: /predict
            Method: post
    Metadata:
      Dockerfile: ./Dockerfile
      DockerContext: ./
      DockerTag: python3.10-v1-1

  RetrainModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 2048
      Timeout: 840
      PackageType: Image
      ImageConfig:
        Command: ['app.lambda_retrain_function']
      # need this to run docker on mac
      # Architectures: ['arm64']
      Environment:
        Variables:
          AMAZON_BUCKET: face-2-simpson-imgs
      Events:
        ApiEndpoint:
          Type: HttpApi
          Properties:
            Path: /retrain
            Method: post
    Metadata:
      Dockerfile: ./Dockerfile
      DockerContext: ./
      DockerTag: python3.10-v1-2

Outputs:
  PredictApi:
    Description: 'API Gateway endpoint URL for Prod stage for predict function'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/predict'
  RetrainApi:
    Description: 'API Gateway endpoint URL for Prod stage for retrain function'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/retrain'
