version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
