name: Deploy PyTorch Model to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'python-server/**'
      - '.github/workflows/sam-pipeline.yml'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Check initial disk space
      - name: Check Disk Space
        run: df -h

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install AWS sam
      - name: Install AWS sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Build SAM application
      - name: Build SAM Application
        run: |
          cd python-server
          sam build --use-container --cached

      # Deploy SAM application
      - name: Deploy SAM Application
        run: |
          cd python-server
          sam deploy
